force-app/main/default/objects/c_LogSetting__mdt/c_LogSetting__mdt.object-meta.xml
<CustomObject>
    <description>Define how the application should generate logs. Mark at least ONE entry as the default setting. Settings may be applied also at the User (User name) OR Profile (Profile ID) level.</description>
    <label>Log Setting</label>
    <pluralLabel>Log Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/c_LogSetting__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Note that a record marked as Default should not be marked inactive!</description>
    <inlineHelpText>Note that a record marked as Default should not be marked inactive!</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

src/objects/c_LogSetting__mdt/fields/Categories__c.field-meta.xml
<CustomField>
    <fullName>Categories__c</fullName>
    <defaultValue>&quot;EVENT, ERROR, INTEGRATION, DATABASE, PROCESS, ALERT, OTHER&quot;</defaultValue>
    <description>Enter a list of categories of log entries that should fire a platform event. Spelling matters! Choose from:
EVENT, ERROR, INTEGRATION, DATABASE, PROCESS, ALERT, OTHER</description>
    <inlineHelpText>Enter a list of categories of log entries that should fire a platform event. Spelling matters! Choose from:
EVENT, ERROR, INTEGRATION, DATABASE, PROCESS, ALERT, OTHER</inlineHelpText>
    <label>Categories firing Platform Events</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/c_LogSetting__mdt/fields/Created__c.field-meta.xml
<CustomField>
    <fullName>Created__c</fullName>
    <defaultValue>Now()</defaultValue>
    <description>Timestamp on creation</description>
    <inlineHelpText>Timestamp on creation</inlineHelpText>
    <label>Created</label>
    <type>DateTime</type>
</CustomField>

src/objects/c_LogSetting__mdt/fields/DebugLogging__c.field-meta.xml
<CustomField>
    <fullName>DebugLogging__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Create a debug log entry for every log entry</description>
    <inlineHelpText>Create a debug log entry for every log entry</inlineHelpText>
    <label>Debug Logging</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/c_LogSetting__mdt/fields/DebugPrefix__c.field-meta.xml
<CustomField>
    <fullName>DebugPrefix__c</fullName>
    <defaultValue>&quot;@@&quot;</defaultValue>
    <description>Text to proceed a debug entry</description>
    <inlineHelpText>Text to proceed a debug entry</inlineHelpText>
    <label>Debug Prefix</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/c_LogSetting__mdt/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Important! At least one entry should be default.</description>
    <inlineHelpText>Important! At least one entry should be default.</inlineHelpText>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/c_LogSetting__mdt/fields/Important__c.field-meta.xml
<CustomField>
    <fullName>Important__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If a log entry is marked as &quot;Important&quot; then it should always fire a platform event</description>
    <inlineHelpText>If a log entry is marked as &quot;Important&quot; then it should always fire a platform event</inlineHelpText>
    <label>Send All Important Entries As Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/c_LogSetting__mdt/fields/limitWarningThreshold__c.field-meta.xml
<CustomField>
    <fullName>limitWarningThreshold__c</fullName>
    <defaultValue>0.75</defaultValue>
    <description>Defines as a percent how high limits should go before they throw a warning. Recommendation is to put this at 75%</description>
    <inlineHelpText>Defines as a percent how high limits should go before they throw a warning. Recommendation is to put this at 75%</inlineHelpText>
    <label>Limit Warning Threshold</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

src/objects/c_LogSetting__mdt/fields/MonitorLimits__c.field-meta.xml
<CustomField>
    <fullName>MonitorLimits__c</fullName>
    <defaultValue>&quot;BASICS&quot;</defaultValue>
    <description>A list of limits to monitor. Choose from:
BASICS,APEX,CALLOUTS,DATABASE</description>
    <inlineHelpText>A list of limits to monitor. Choose from:
BASICS,APEX,CALLOUTS,DATABASE</inlineHelpText>
    <label>Limits to Monitor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/c_LogSetting__mdt/fields/Profile_ID__c.field-meta.xml
<CustomField>
    <fullName>Profile_ID__c</fullName>
    <description>OPTIONAL Use the ID of the a given profile to have specific log settings for them</description>
    <inlineHelpText>OPTIONAL Use the ID of the a given profile to have specific log settings for them</inlineHelpText>
    <label>Profile ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/c_LogSetting__mdt/fields/UserName__c.field-meta.xml
<CustomField>
    <fullName>UserName__c</fullName>
    <description>OPTIONAL The full username ex. sarah.exec@company.org.sandboxname. Use this to have a particular set up for a specific user.</description>
    <inlineHelpText>OPTIONAL The full username ex. sarah.exec@company.org.sandboxname. Use this to have a particular set up for a specific user.</inlineHelpText>
    <label>User Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

src/classes/c_Log_Test.cls
/**
 @Name: c_Log_Test.cls
 @Tests: c_Log.cls
 @Description: Tests Logging Framework. Cannot test publishing of platform event!
 @History
  VERSION     AUTHOR           DATE            DETAIL
  1.0         Matt Evans       28/8/2019       Draft
*/

@IsTest
private class c_Log_Test extends c_TestFactory {

    /**
    * Ensure custom metadata has a default value
    */
    @IsTest
    static void checkSettings() {
        // Ensure the code gives values for these constants
        System.Assert(c_log.DEBUG_PREFIX!=null,'DEBUG_PREFIX not set');
        System.Assert(c_log.DEBUG_LOGGING!=null,'DEBUG_LOGGING not set');
        System.Assert(c_log.EVENT_CATEGORIES!=null,'EVENT_CATEGORIES not set');
        System.Assert(c_log.SEND_ALL_IMPORTANT_EVENTS!=null,'SEND_ALL_IMPORTANT_EVENTS not set');
        System.Assert(c_log.MONITOR_LIMITS!=null,'MONITOR_LIMITS not set');
        System.Assert(c_log.LIMIT_WARNING_THRESHOLD!=null,'LIMIT_WARNING_THRESHOLD not set');

        // Check the options are set in for default in settings
        c_LogSetting__mdt[] matchingOptions;
        matchingOptions = [SELECT 
                Default__c,  UserName__c, Profile_ID__c,
                DebugLogging__c, DebugPrefix__c, 
                Categories__c, 
                Important__c,
                MonitorLimits__c,
                limitWarningThreshold__c
                FROM c_LogSetting__mdt WHERE Default__c = TRUE and Active__c = TRUE Order By Created__c DESC limit 1];
        System.Assert(matchingOptions!=null && !matchingOptions.isEmpty(), 'Custom metadata c_LogSetting__mdt is MISSING a default logging entry. This will conflate DML and cause errors in your org. Go to ther custom metadata in setup and create an entry for this object flagged with field "Default" checked');
    }

    /**
    * Check settings can vary for User and Profile Id
    */
    @IsTest
    static void test_userCanDefineSettings() {
        setDefaultContext();

        User admin = (User) make(Entity.ADMIN_USER, new User(alias='theAdmin'));
        run();

        // In memory only test for settings
        c_LogSetting__mdt matchingOptionUser = new c_LogSetting__mdt(DeveloperName= 'TestUser', UserName__c = admin.UserName);
        c_LogSetting__mdt matchingOptionProfile = new c_LogSetting__mdt(DeveloperName= 'TestProfile', Profile_ID__c = admin.ProfileId);
        c_LogSetting__mdt matchingOptionDefault = new c_LogSetting__mdt(DeveloperName= 'TestDefault', Default__c = TRUE);

        c_LogSetting__mdt options;
        options = c_Log.compareOptions(new List<c_LogSetting__mdt>{matchingOptionUser}, admin.UserName, admin.ProfileId);
        System.Assert(options!=null,'Logging method did not find logging options based on User Name. Logical fault in c_Log.matchOptions.');

        options = c_Log.compareOptions(new List<c_LogSetting__mdt>{matchingOptionProfile}, admin.UserName, admin.ProfileId);
        System.Assert(options!=null,'Logging method did not find logging options based on ProfileId. Logical fault in c_Log.matchOptions.');

        options = c_Log.compareOptions(new List<c_LogSetting__mdt>{matchingOptionDefault}, admin.UserName, admin.ProfileId);
        System.Assert(options!=null,'Logging method did not find logging options based on Default. Logical fault in c_Log.matchOptions.');
    }


    /**
    * Test push events & create log entries
    */
    @IsTest
    static void test_pushEvents() {
        // No matter the settings these should fire gracefully. Running this should provide debug logs etc. according to the options. No way to test platform events in memory, so we have to be happy with coverage :()
        c_Log.push('Test Message');
        c_Log.push(c_Log.category.OTHER, 'Test Important Categorised Message', true);
        c_Log.push(c_Log.category.DATABASE, 'A database error', 'my soql string', true);
        c_Log.push('Test Generic Important Message', true);
        c_Log.emit();

        c_Log.push('Test Message');
        c_log.flush();
    }
}